# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcache',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardcache',
            index=models.Index(fields=['cache_key', 'is_valid'], name='reports_das_cache_k_11f0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardcache',
            index=models.Index(fields=['expires_at'], name='reports_das_expires_4d872a_idx'),
        ),
    ]
