# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['reference_code'], name='contracts_i_referen_485f40_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='contracts_i_status_65e4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='contracts_i_due_dat_1e9c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['reference_code'], name='contracts_c_referen_b8eae4_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['signing_token'], name='contracts_c_signing_4e91ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'),
        ),
    ]
