# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('is_immutable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=20, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_request', to='payouts.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
