# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['reference_code'], name='payouts_pay_referen_1832c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['admin_user', 'status'], name='payouts_pay_admin_u_49918a_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='payouts_pay_created_b65d12_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_pay_status_a5ad2e_idx'),
        ),
    ]
