# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField()),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_immutable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['document_code', 'verified_at'], name='verificatio_documen_2ae13c_idx')],
            },
        ),
    ]
