# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['reference_code'], name='quotes_quot_referen_00ec7b_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_quot_status_bc6cd2_idx'),
        ),
    ]
