# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/pdfs/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('DOWNLOADED', 'Downloaded'), ('EMAIL_SENT', 'Email Sent')], default='GENERATED', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_immutable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
