# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['reference_code'], name='receipts_re_referen_51e0be_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['transaction'], name='receipts_re_transac_f0c0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='receipts_re_status_ce247e_idx'),
        ),
    ]
