# Generated by Django 4.2.28 on 2026-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUEST', 'Password Reset Requested'), ('PASSWORD_RESET_ADMIN', 'Password Reset by Admin'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYOUT_INITIATED', 'Payout Initiated'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed'), ('QUOTE_CREATED', 'Quote Created'), ('QUOTE_SENT', 'Quote Sent'), ('CONTRACT_CREATED', 'Contract Created'), ('CONTRACT_SIGNED', 'Contract Signed'), ('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_SENT', 'Invoice Sent'), ('RECEIPT_GENERATED', 'Receipt Generated'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('UNKNOWN', 'Unknown Action')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_immutable', models.BooleanField(default=True, editable=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
